### ISSUE TITLE
Where to get the "conll03，ontonotes，ptb" dataset?

### ISSUE THREAD

**Issue by imsheridan** [choosewhatulike/sparse-sharing#1]
Dear author,

I'm trying to repro your algo but it seems I don't know how to get these three datasets before I can run the pre-processing code below. Could you pls point out how I can get them? Thx
>  python prepare-data.py \
>   --type conll03 \
>   --pos /path/to/pos \
>   --chunk /path/to/chunk \
>   --ner /path/to/ner

**Comment by txsun1997** [comment]
refer to your email

**Comment by wangxu-scu** [comment]
Hello, thx for your code! Can you also help me to get the three datasets?

**Comment by lichunnan** [comment]
hello,thanks for your work~And can you also help me to get the three datasets?

**Comment by txsun1997** [comment]
Thanks for your attention. Send me an email (txsun19@fudan.edu.cn), I'll reply with the datasets attached.

**Comment by choosewhatulike** [comment]
Sorry for the late reply. We upload the conll03 and PTB datasets to the repo (see `./data` folder for details). And due to the copyright of the OntoNotes dataset, we cannot upload it to the public.

**Comment by ax-22** [comment]
Thanks for sharing. I understand the copyright of the OntoNotes dataset. But is it possible to provide the code for preparing OntoNotes?

**Comment by txsun1997** [comment]
See https://github.com/yhcc/OntoNotes-5.0-NER. Hope it helps.
