### ISSUE TITLE
项目在哪个部分进行子网络mask更新？

### ISSUE THREAD

**Issue by lichunnan** [choosewhatulike/sparse-sharing#2]
您好，非常感谢您的贡献！我想了解下，在程序哪个部分进行mask矩阵的更新，我跑了程序看程序的mask矩阵始终是全false。如果没理解错的化，masker类中after_forward（），before_forward（）都是在进行mask更新model的parameters只不过一个是在更新全部和一个是在更新有梯度的，为啥这么设计啊？

**Comment by txsun1997** [comment]
需要先单任务进行剪枝，可以给我们看下你执行的命令行依次是什么吗？按照readme的顺序应当没有问题（`bash run_conll03.sh single`会生成mask矩阵）

**Comment by lichunnan** [comment]
额~~~我还没运行单任务，直接运行的多任务，我重跑下在请教你，谢谢~~~~
